* import_knowledge_test.do
* this is the do file automatically generated by SurveyCTO !!
*
* 	Imports and aggregates "Knowledge test for ODH nurses" (ID: knowledge_test) data.
*
*	Inputs:  "Knowledge test for ODH nurses_WIDE.csv"
*	Outputs: "Knowledge test for ODH nurses.dta"
*
*	Output by SurveyCTO December 12, 2025 11:28 AM.
*****************************************



* import data from primary .csv file
import excel "$bl_test/Knowledge test for ODH nurses_WIDE.xlsx", sheet("data") firstrow clear
rename *, lower



* initialize form-specific parameters
local csvfile "Knowledge test for ODH nurses_WIDE.xlsx"
local dtafile "Knowledge test for ODH nurses.dta"
local corrfile "Knowledge test for ODH nurses_corrections.csv"
local note_fields1 ""
local text_fields1 "deviceid devicephonenum username device_info duration caseid provider_name facility_odh_other case1p1_diag1_oth case1p1_diag2_oth case1p1_diag3_oth case1p1_diag4_oth case1p1_questions"
local text_fields2 "case1p1_questions_oth case1p2_diag1_oth case1p2_diag2_oth case1p2_diag3_oth case1p2_diag4_oth case1p2_questions case1p2_questions_oth case2p1_diag1_oth case2p1_diag2_oth case2p1_diag3_oth"
local text_fields3 "case2p1_diag4_oth case2p1_questions case2p1_questions_oth case2p2_diag1_oth case2p2_diag2_oth case2p2_diag3_oth case2p2_diag4_oth case2p2_diag5_oth case2p2_questions case2p2_questions_oth"
local text_fields4 "tx_pneumonia_woman tx_pneumonia_woman_other tx_tb_suspected_man tx_tb_suspected_man_other tx_malaria_child tx_malaria_child_other tx_ulcer_adult tx_ulcer_adult_other tx_sti_suspected_man"
local text_fields5 "tx_sti_suspected_other comments instanceid"
local date_fields1 ""
local datetime_fields1 "submissiondate starttime endtime"






* drop extra table-list columns
cap drop reserved_name_for_field_*
cap drop generated_table_list_lab*


	* drop note fields (since they don't contain any real data)
	forvalues i = 1/100 {
		if "`note_fields`i''" ~= "" {
			drop `note_fields`i''
		}
	}
	
	* format date and date/time fields
	forvalues i = 1/100 {
		if "`datetime_fields`i''" ~= "" {
			foreach dtvarlist in `datetime_fields`i'' {
				cap unab dtvarlist : `dtvarlist'
				if _rc==0 {
					foreach dtvar in `dtvarlist' {
						tempvar tempdtvar
						rename `dtvar' `tempdtvar'
						gen double `dtvar'=.
						cap replace `dtvar'=clock(`tempdtvar',"MDYhms",2025)
						* automatically try without seconds, just in case
						cap replace `dtvar'=clock(`tempdtvar',"MDYhm",2025) if `dtvar'==. & `tempdtvar'~=""
						format %tc `dtvar'
						drop `tempdtvar'
					}
				}
			}
		}
		
	}

	
	

	

	* label variables
	label variable key "Unique submission ID"
	cap label variable submissiondate "Date/time submitted"
	cap label variable formdef_version "Form version used on device"
	cap label variable review_status "Review status"
	cap label variable review_comments "Comments made during review"
	cap label variable review_corrections "Corrections made during review"


	label variable fieldworker_name "Name of the person entering the data:"
	label define fieldworker_name 1 "Pamella" 2 "Brian" -97 "Other"
	label values fieldworker_name fieldworker_name

	label variable provider_name "Name of the nurse"
	label variable provider_gender "Gender of the nurse"
	label define provider_gender 1 "Male" 2 "Female"
	label values provider_gender provider_gender
	label variable facility_odh "Name of the clinic where the nurse works"
	label define facility_odh 11101 "Abura" 11110 "Acoyo Wakadogo" 11130 "Adem" 21142 "Agule" 11116 "Aloto" 11121 "Alwee" 11123 "Alworo" 21137 "Aritei" 11129 "Atali/Aweiwot" 11132 "Atana" 11125 "Awac" 21143 "Awoja Kanyangang" 11135 "Barlongo" 11102 "Bobi" 11122 "Boke" 11133 "Chakali" 11126 "Chwagere" 11115 "Corner Kalabong" 11124 "Dumakuc" 21140 "Kacherede" 11119 "Kalili" 21139 "Kameno" 21145 "Kamurojo" 11120 "Kazi Kazi" 11108 "Laminadera" 11105 "Lukai" 11106 "Lutuk" 11112 "Mede" 11134 "Myene" 11111 "Nyapeya" 21136 "Obur" 11109 "Ocim" 21146 "Odapakol" 11127 "Ojul" 11103 "Okwir" 21138 "Omasia" 11117 "Ongakotuke" 21144 "Onyait" 11114 "Pwunu Dyang" 11107 "St Andrew" 11131 "Te-ogali" 11113 "Te-Olam" 21141 "Totolim" 11118 "Wao" 11104 "Wii Lacor" -97 "Other"
	label values facility_odh facility_odh

	label variable facility_odh_other "Enter other name"	
	label variable versionab "Which questionnaire did the nurse do?"	
	label define versionab 1 "A" 2 "B"
	label values versionab versionab
	label variable case1p1_diag1 "1. Most likely diagnosis"	
	label define case1p1_diag1 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p1_diag1 case1p1_diag1
	label variable case1p1_diag1_oth "1. Most likely diagnosis (other)"
	label variable case1p1_diag2 "2. Second most likely diagnosis"
	label define case1p1_diag2 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p1_diag2 case1p1_diag2
	label variable case1p1_diag2_oth "2. Second most likely diagnosis (other)"
	label variable case1p1_diag3 "3. Third most likely diagnosis"
	label define case1p1_diag3 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p1_diag3 case1p1_diag3
	label variable case1p1_diag3_oth "3. Third most likely diagnosis (other)"
	label variable case1p1_diag4 "4. Fourth most likely diagnosis"	
	label define case1p1_diag4 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p1_diag4 case1p1_diag4
	label variable case1p1_diag4_oth "4. Fourth most likely diagnosis (other)"
	label variable case1p1_questions "What questions would you ask the patient about her problem?"	
	label variable case1p1_questions_oth "List the other questions"
	label variable case1p2_diag1 "1. Most likely diagnosis"	
	label define case1p2_diag1 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p2_diag1 case1p2_diag1
	label variable case1p2_diag1_oth "1. Most likely diagnosis (other)"
	label variable case1p2_diag2 "2. Second most likely diagnosis"
	label define case1p2_diag2 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p2_diag2 case1p2_diag2
	label variable case1p2_diag2_oth "2. Second most likely diagnosis (other)"
	label variable case1p2_diag3 "3. Third most likely diagnosis"	
	label define case1p2_diag3 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p2_diag3 case1p2_diag3
	label variable case1p2_diag3_oth "3. Third most likely diagnosis (other)"
	label variable case1p2_diag4 "4. Fourth most likely diagnosis"
	label define case1p2_diag4 0 "None written" 1 "Pneumonia" 2 "URTI" 3 "COPD" 4 "Asthma" 5 "TB" -97 "Other"
	label values case1p2_diag4 case1p2_diag4
	label variable case1p2_diag4_oth "4. Fourth most likely diagnosis (other)"
	label variable case1p2_questions "What further questions would you ask the patient about her problem, if any?"
	label variable case1p2_questions_oth "List the other questions"
	label variable case2p1_diag1 "1. Most likely diagnosis"
	label define case2p1_diag1 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p1_diag1 case2p1_diag1
	label variable case2p1_diag1_oth "1. Most likely diagnosis (other)"
	label variable case2p1_diag2 "2. Second most likely diagnosis"
	label define case2p1_diag2 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p1_diag2 case2p1_diag2
	label variable case2p1_diag2_oth "2. Second most likely diagnosis (other)"
	label variable case2p1_diag3 "3. Third most likely diagnosis"
	label define case2p1_diag3 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p1_diag3 case2p1_diag3
	label variable case2p1_diag3_oth "3. Third most likely diagnosis (other)"
	label variable case2p1_diag4 "4. Fourth most likely diagnosis"
	label define case2p1_diag4 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p1_diag4 case2p1_diag4
	label variable case2p1_diag4_oth "4. Fourth most likely diagnosis (other)"
	label variable case2p1_questions "What questions would you ask the patient about his problem?"
	label variable case2p1_questions_oth "List the other questions"
	label variable case2p2_diag1 "1. Most likely diagnosis"
	label define case2p2_diag1 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p2_diag1 case2p2_diag1
	label variable case2p2_diag1_oth "1. Most likely diagnosis (other)"
	label variable case2p2_diag2 "2. Second most likely diagnosis"	
	label define case2p2_diag2 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p2_diag2 case2p2_diag2
	label variable case2p2_diag2_oth "2. Second most likely diagnosis (other)"
	label variable case2p2_diag3 "3. Third most likely diagnosis"
	label define case2p2_diag3 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p2_diag3 case2p2_diag3
	label variable case2p2_diag3_oth "3. Third most likely diagnosis (other)"
	label variable case2p2_diag4 "4. Fourth most likely diagnosis"
	label define case2p2_diag4 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p2_diag4 case2p2_diag4
	label variable case2p2_diag4_oth "4. Fourth most likely diagnosis (other)"
	label variable case2p2_diag5 "5. Fifth most likely diagnosis"
	label define case2p2_diag5 0 "None written" 1 "STI" 2 "UTI" 3 "Candidiasis" 4 "Gonorrhea" 5 "Syphilis" 6 "Chlamydia" -97 "Other"
	label values case2p2_diag5 case2p2_diag5
	label variable case2p2_diag5_oth "5. Fifth most likely diagnosis (other)"
	label variable case2p2_questions "What further questions would you ask the patient about his problem, if any?"
	label variable case2p2_questions_oth "List the other questions"
	label variable tx_pneumonia_woman "Woman with pneumonia"
	label variable tx_pneumonia_woman_other "Other treatment:"
	label variable tx_tb_suspected_man "Man with suspected tuberculosis"
	label variable tx_tb_suspected_man_other "Other treatment:"
	label variable tx_malaria_child "Child with malaria"
	label variable tx_malaria_child_other "Other treatment:"
	label variable tx_ulcer_adult "Adult with stomach ulcer"
	label variable tx_ulcer_adult_other "Other treatment:"
	label variable tx_sti_suspected_man "Man with suspected STI (penile discharge)"
	label variable tx_sti_suspected_other "Other treatment:"
	label variable comments "Any comments?"




lab var case1p1_questions_0 "No questions" 
lab var case1p1_questions_1 "more questions about the cough (day or night, how long it goes on)" 
lab var case1p1_questions_2 "is cough productive"  			
lab var case1p1_questions_3 "difficulty breathing"  		
lab var case1p1_questions_4 "any fever"  
lab var case1p1_questions_5 "have taken medicines"  
lab var case1p1_questions_6 "HIV status"  
lab var case1p1_questions_7 "cough up blood"  		
lab var case1p1_questions_8 "more about the sputum (colour, frequency)"  		
lab var case1p1_questions_9 "allergies"  
lab var case1p1_questions_10 "wheezing"  
lab var case1p1_questions_11 "tired / fatigue"  
lab var case1p1_questions_12 "sweat at night"  
lab var case1p1_questions_13 "is appetite normal"  		
lab var case1p1_questions_14 "lost weight"  
lab var case1p1_questions_15 "anyone around also coughs"  
lab var case1p1_questions__97 "Other"


lab var case1p2_questions_0 "No questions" 
lab var case1p2_questions_1 "more questions about the cough (day or night, how long it goes on)" 
lab var case1p2_questions_2 "is cough productive"  			
lab var case1p2_questions_2 "is cough productive"           
lab var case1p2_questions_3 "difficulty breathing"          
lab var case1p2_questions_4 "any fever"  
lab var case1p2_questions_5 "have taken medicines"  
lab var case1p2_questions_6 "HIV status"  
lab var case1p2_questions_7 "cough up blood"        
lab var case1p2_questions_8 "more about the sputum (colour, frequency)"         
lab var case1p2_questions_9 "allergies"  
lab var case1p2_questions_10 "wheezing"  
lab var case1p2_questions_11 "tired / fatigue"  
lab var case1p2_questions_12 "sweat at night"  
lab var case1p2_questions_13 "is appetite normal"       
lab var case1p2_questions_14 "lost weight"  
lab var case1p2_questions_15 "anyone around also coughs"  
lab var case1p2_questions__97 "Other"



lab var case2p1_questions_0 "No questions"  
lab var case2p1_questions_1 "how long had the problem/when it started"  
lab var case2p1_questions_2 "pain / burning on urinating"  
lab var case2p1_questions_3 "how many recent sexual partners"  
lab var case2p1_questions_4 "if you have unprotected sex?"  
lab var case2p1_questions_5 "how often discharge comes out"  
lab var case2p1_questions_6 "about the smell of the discharge"   
lab var case2p1_questions_7 "about what the discharge looks like"  
lab var case2p1_questions_8 "HIV status"  
lab var case2p1_questions_9 "any partners who have symptoms"  
lab var case2p1_questions_10 "stomach pain"  
lab var case2p1_questions_11 "testicle pain"  
lab var case2p1_questions_12 "any sores/lesions on the penis"  
lab var case2p1_questions_13 "if had anything like this before"  
lab var case2p1_questions_14 "pain during sex"  
lab var case2p1_questions_15 "any fever"     
lab var case2p1_questions__97 "Other"

lab var case2p2_questions_0 "No questions"
lab var case2p2_questions_1 "how long had the problem/when it started"
lab var case2p2_questions_2 "pain / burning on urinating"
lab var case2p2_questions_3 "how many recent sexual partners"
lab var case2p2_questions_4 "if you have unprotected sex?"
lab var case2p2_questions_5 "how often discharge comes out"
lab var case2p2_questions_6 "about the smell of the discharge"
lab var case2p2_questions_7 "about what the discharge looks like"
lab var case2p2_questions_8 "HIV status"
lab var case2p2_questions_9 "any partners who have symptoms"
lab var case2p2_questions_10 "stomach pain"
lab var case2p2_questions_11 "testicle pain"
lab var case2p2_questions_12 "any sores/lesions on the penis" 
lab var case2p2_questions_13 "if had anything like this before"
lab var case2p2_questions_14 "pain during sex"
lab var case2p2_questions_15 "any fever"
lab var case2p2_questions__97 "Other"


lab var tx_ulcer_adult_1 "MAGNESIUM tablets, 2 tabs TDS for 5/7" 
lab var tx_ulcer_adult_2 "MAGNESIUM (not specified / other)" 
lab var tx_ulcer_adult_3 "OMEPRAZOLE 20mg BD for 7/7"		
lab var tx_ulcer_adult_4 "OMEPRAZOLE (not specified / other)" 
lab var tx_ulcer_adult_5 "METRONIDAZOLE 400mg TDS for 7/7" 
lab var tx_ulcer_adult_6 "METRONIDAZOLE (not specified / other)" 
lab var tx_ulcer_adult_7 "AMOXICILLIN 500mg TDS for 7/7" 
lab var tx_ulcer_adult_8 "AMOXICILLIN (not specified / other)" 
lab var tx_ulcer_adult__97 "Other"


lab var  tx_sti_suspected_man_1 " Test for HIV"
lab var  tx_sti_suspected_man_2	"Ceftriaxone 500 IV/IM STAT"
lab var  tx_sti_suspected_man_3	"Ceftriaxone (not specified / other)"
lab var  tx_sti_suspected_man_4	"Doxycycline 500mg PO BD 7/7"
lab var  tx_sti_suspected_man_5	"Doxycycline 100mg"
lab var  tx_sti_suspected_man_6	"Doxycycline (not specified / other)"
lab var  tx_sti_suspected_man__97	"Other"

lab var  tx_tb_suspected_man_1 "Refer for tests"
lab var  tx_tb_suspected_man__97 "Other"

lab var tx_malaria_child_1 "Artemether-Lumefantrine (AL) dose according to weight"
lab var tx_malaria_child_2 "Paracetamol / ibuprofen"
lab var tx_malaria_child__97 "Other"


** compute total scores for knowledge test (questions asked)**


drop case2p2_questions_0 case2p1_questions_0 case1p1_questions_0 case1p2_questions_0
egen  case1p1_questions_sum = rowtotal(case1p1_questions_1-case1p1_questions__97)
egen  case1p2_questions_sum = rowtotal(case1p2_questions_1-case1p2_questions__97)
egen  case2p1_questions_sum = rowtotal(case2p1_questions_1-case2p1_questions__97)
egen  case2p2_questions_sum = rowtotal(case2p2_questions_1-case2p2_questions__97)

label variable case1p1_questions_sum "Total number of questions asked - Case 1 Part 1"
label variable case1p2_questions_sum "Total number of questions asked - Case 1 Part 2"
label variable case2p1_questions_sum "Total number of questions asked - Case 2 Part 1"
label variable case2p2_questions_sum "Total number of questions asked - Case 2 Part 2"
